# .streamlit/secrets.toml

[connections.snowflake]
account = "mub55911.snowflakecomputing.com"
user = "admin"
password = "Welcome200"
role = "ACCOUNTADMIN
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true