# .streamlit/secrets.toml

[connections.snowflake]
account = "DZEOXZF-OA00850"
user = "github"
password = "4UZgLhRStVBRBBt"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
